### PR TITLE
Use rsconnect-python

### PR DESCRIPTION
**Pull request by mmarchetti**
### Description

This PR introduces a dependency on the new rsconnect-python package. These are in separate packages because rsconnect-python has minimal dependencies and provides a CLI, while this package depends on Jupyter.

Notes: rsconnect-python isn't released on PyPI at this time. This PR temporarily installs it from test-pypi into to the dev environment for testing. We need to release rsconnect-python first, and then this package (for releases done after this PR lands).

You may notice that there are no longer any unit tests, because all of the existing tests were associated with the modules that were moved to rsconnect-python. I'm working on a PR to factor the API handler into inidividual functions which will be easier to test.

Connected to #https://github.com/rstudio/connect/issues/15839

### Testing Notes / Validation Steps
* Exercise all features, on both python 2 and 3, since the entire `api`, `bundle`, and `environment` modules have been refactored out of this package and into rsconnect-python.

### CODE REVIEW

**Comment by mmarchetti** [comment]
@scottmmjackson This should be ready for review now that it's been updated for the latest changes to rsconnect-python.

**Comment by scottmmjackson** [comment]
The sticky session bug in here might hurt us. I think we should fix that.

**Comment by mmarchetti** [comment]
Agreed, let's hold off on merging until that's fixed.

**Comment by scottmmjackson** [comment]
@mmarchetti This might be ready to merge. I popped the cookies on the deploy endpoint return value so the log follower works now.

I'm going to approve and leave it up to you to merge if you feel confident that nothing else needs to be addressed in that sphere.

**Pull request merged**
