### PR TITLE
Rebranding

### PR DESCRIPTION
**Pull request by whimsicallyson**
### Description
Updates company name and grammar throughout. Additionally, adds CSS and header/footer overrides to docs in order to match other docs on the site. Updated screenshots in the docs as well.

Leaves historical references to RStudio Connect in NEWS intact.

Also not sure if I should loop any non-Content Engagement folks into these reviews? 🤷‍♀️

Connected to https://github.com/rstudio/connect/issues/21954

### Testing Notes / Validation Steps

I'd recommend attempting to deploy a Jupyter notebook to Connect to make sure all relevant references to RStudio are switched to Posit, and building the docs and comparing the styling to docs.rstudio.com

### CODE REVIEW

**Comment by whimsicallyson** [comment]
@mmarchetti I added you to this review so that someone who has been involved with the rsconnect-jupyter repo in the past can take a look. If that's not you, let me know who I should tag instead!

**Review by AshleyHenry15 — APPROVED** [review]
LGTM

**Review by mmarchetti — APPROVED** [review]

**Comment by whimsicallyson** [comment]
note: there's a video [here](https://github.com/rstudio/rsconnect-jupyter/blob/21954-rebranding/docs/docs/additional.md) that I don't know anything about updating....

**Comment by nkakade-rstudio** [comment]
Found one instance of RStudio Connect in the docs: 

Screen Shot 2022-10-11 at 12 50 08 PM

**Comment by whimsicallyson** [comment]
@Lytol linting issue I mentioned in our content engagement meeting

**Review by AshleyHenry15 — APPROVED** [review]

**Pull request merged**
